repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.74.1
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
      args:
        - --args=--lockfile=false         # Disable lockfile check, should be used only for Terraform modules!
    - id: terraform_validate
    - id: terraform_tflint
    - id: terraform_checkov
      args:
        - --args=--quiet
        - --args=--download-external-modules true
        - --args=--skip-check CKV_TF_1    # Ensure Terraform module sources use a commit hash
        - --args=--skip-check CKV_AWS_73  # Ensure API Gateway has X-Ray Tracing enabled
        - --args=--skip-check CKV_AWS_120 # Ensure API Gateway caching is enabled
        - --args=--skip-check CKV_AWS_149 # Ensure that Secrets Manager secret is encrypted using KMS CMK
        - --args=--skip-check CKV_AWS_158 # AWS CloudWatch Log groups encrypted using default encryption key instead of KMS CMK
        - --args=--skip-check CKV_AWS_225 # Ensure API Gateway method setting caching is enabled
        - --args=--skip-check CKV_AWS_272 # Ensure AWS Lambda function is configured to validate code-signing
        - --args=--skip-check CKV_AWS_338 # AWS CloudWatch log groups retention set to less than 365 days
        - --args=--skip-check CKV2_AWS_4  # Ensure API Gateway stage have logging level defined as appropriate
        - --args=--skip-check CKV2_AWS_29 # Ensure public API gateway are protected by WAF
        - --args=--skip-check CKV2_AWS_51 # Ensure AWS API Gateway endpoints uses client certificate authentication
        - --args=--skip-check CKV2_AWS_57 # Ensure Secrets Manager secrets should have automatic rotation enabled

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-added-large-files
